### ISSUE TITLE
After clicking on Sign up option in Register ,Nothing is happening

### ISSUE THREAD

**Issue by AatifSalim** [1209simran/Land-Registry-Application#8]
Hi Simran ,
I am not able to sign up in register option as I click on the sign up button nothing happe
![Screenshot (30)](https://user-images.githubusercontent.com/86012528/149071629-11215cb8-babe-4208-bb9e-edfb70e4d839.png)
n

**Comment by 1209simran** [comment]
In the Private Key field, you should enter the account address.

**Comment by AatifSalim** [comment]
Can you please share me your Email Address

**Comment by AatifSalim** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/86012528/149295047-c229a9d3-1881-4a15-9588-9cb1cfe491c5.png)
![Screenshot (33)](https://user-images.githubusercontent.com/86012528/149295058-7c11359a-ee0e-4af7-9818-2da68201114b.png)

**Comment by 1209simran** [comment]
- The email address that you've entered already exists in the database. Try using another email address. 
- To resolve the second error, you've to first run the server and then run the curl command. Follow the steps mentioned in the readme file.

**Comment by AatifSalim** [comment]
Thank You ,
Project is Running now :)

**Comment by ayazwani** [comment]
Facing the same issue. When I Try to Register a user it shows the user already exists. Don't know what's happening. And from other terminals, it's showing **no primary server available** when connecting to MongoDB client. Can anyone help?

**Comment by 1209simran** [comment]
@ayazwani, please check whether you're connected to MongoDB or not.

**Comment by prithvi669** [comment]
> 

can u help me bro .. pls reply asap

**Comment by mofirojean** [comment]
I had issues registering as mind gives me the error 
 
```javascript
{
    "code": -32603,
    "message": "Internal JSON-RPC error.",
    "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:3:5698)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:3:8789)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:3:9398)\\n    at Xt.X (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:297907)\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:1:59084\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:1:270605\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:3:85134\"\n}\n  at new o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:3:5698)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:3:8789)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:3:9398)\n  at Xt.X (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:297907)\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:1:59084\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:1:270605\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:3:85134"
}
``` 

<img width="1913" height="1008" alt="Image" src="https://github.com/user-attachments/assets/64a7b4d1-8a0b-413e-a912-06371db16b0b" />

<img width="1913" height="1008" alt="Image" src="https://github.com/user-attachments/assets/1bc74212-1d1f-4ae5-8593-116fa2433da5" />
